(version 2)
((previous_entries
  ((rss.rss ((id ())))
   (no_title.rss ())
   (https://some-website/relative.rss ())
   (https://some-website/relative.atom ())
   (error.rss ())
   (empty.rss ())
   (content_type.atom ())
   (atom.atom ())
   (./no_title.rss ())
   (./empty.rss ())
   (././rss.rss ())
   (././no_title.rss ())
   (././empty.rss ())
   (./././rss.rss ())
   (././././rss.rss ())
   (./././././rss.rss ())
   (././././././rss.rss ())
   (./././././././rss.rss ())
   (././././././././rss.rss ())))
 (next_update
  ((rss.rss 12345678) (no_title.rss 0)
   (https://some-website/relative.rss 0)
   (https://some-website/relative.atom 0)
   (error.rss 0)
   (empty.rss 0)
   (content_type.atom 0)
   (atom.atom 0)
   (./no_title.rss 0)
   (./empty.rss 0)
   (././rss.rss 0)
   (././no_title.rss 0)
   (././empty.rss 0)
   (./././rss.rss 0)
   (././././rss.rss 0)
   (./././././rss.rss 0)
   (././././././rss.rss 0)
   (./././././././rss.rss 0)
   (././././././././rss.rss 0)))
 (page_contents ()) (unsent_mails ()))
