((feed_data
  ((atom.atom 0 ())
   (rss.rss 12345678 ((id ())))
   (././rss.rss 0 ())
   (./././rss.rss 0 ())
   (firefox.html 0 ((0.2.html ())))
   (no_title.rss 0 ())
   (content_type.atom 0 ())
   (dune_blog.html 0 ())
  ))
 (unsent_mails ()))
