((feed_data
  ((atom.atom 0 ())
   (rss.rss 12345678 (id))
   (././rss.rss 0 ())
   (./././rss.rss 0 ())
   (./././rss.rss 0 ())
   (no_title.rss 0 ())
   (./no_title.rss 0 ())
   (././no_title.rss 0 ())
   (././././rss.rss 0 ())
   (./././././rss.rss 0 ())
   (././././././rss.rss 0 ())
   (content_type.atom 0 ())
   (https://some-website/relative.atom 0 ())
   (https://some-website/relative.rss 0 ())
   (./././././././rss.rss 0 ())
   (error.rss 0 ())
  )))
