### This file is generated by opam2nix.

self:
let
    lib = self.lib;
    pkgs = self.pkgs;
    selection = self.selection;
    repoPath = self.repoPath;
    repos = 
    {
      opam-repository = 
      rec {
        fetch = 
        {
          owner = "ocaml";
          repo = "opam-repository";
          rev = "882b3d139f5675109f782f1de8f79b358c5d734b";
          sha256 = "1d1gr9xqkzbfg0lb2amnbm4kpmhbzzpm5z22jrhv6c4yddk9w50r";
        };
        src = (pkgs.fetchFromGitHub) fetch;
      };
    };
in
{
  format-version = 4;
  inherit repos;
  ocaml-version = "4.10.2";
  selection = 
  {
    angstrom = 
    {
      pname = "angstrom";
      version = "0.15.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/angstrom/archive/0.15.0.tar.gz";
        sha256 = "01cjjal8vjsm225v9y0q6ixam8k5f821rcr6yix6i9nzs84aq6gi";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml-syntax-shims ocaml dune bigstringaf;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/angstrom/angstrom.0.15.0";
        hash = "sha256:07ryik3g3hz79hnfdwxdh2jsw3cmbgygjs7mjdw07p927wkd83k9";
      };
    };
    asn1-combinators = 
    {
      pname = "asn1-combinators";
      version = "0.2.6";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-asn1-combinators/releases/download/v0.2.6/asn1-combinators-v0.2.6.tbz";
        sha256 = "148s3clqws2nmzwhvlgy0b3nnvq2xbw1qb3mcc865vv9i06xwah1";
      };
      opamInputs = 
      {
        inherit (selection) zarith ptime ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/asn1-combinators/asn1-combinators.0.2.6";
        hash = "sha256:03s1aska9ws9pnjm3v7f69qcx5gdmjh53ximh5zy9v9vf2sxbdsr";
      };
    };
    astring = 
    {
      pname = "astring";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/astring/releases/astring-0.8.5.tbz";
        sha256 = "1ykhg9gd3iy7zsgyiy2p9b1wkpqg9irw5pvcqs3sphq71iir4ml6";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/astring/astring.0.8.5";
        hash = "sha256:1djnad9sq12idlakj069xvwm2nn7wqm137pqbxxai5frkgi08x74";
      };
    };
    base = 
    {
      pname = "base";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/base/archive/v0.14.1.tar.gz";
        sha256 = "13b0xc62ka8i2ry2r62gc194wzfdq1vqf2qygwrrk26pvqn8a9l9";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune-configurator dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base/base.v0.14.1";
        hash = "sha256:014xlh33ayf440lf9yx62z43q9977254911p3jyncw2hrmarny4h";
      };
    };
    base-bytes = 
    {
      pname = "base-bytes";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-bytes/base-bytes.base";
        hash = "sha256:0a68lmbf68jgm1i3b59j2sc3ha9yhv4678f9mfwwvczw88prq7l3";
      };
    };
    base-threads = 
    {
      pname = "base-threads";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-threads/base-threads.base";
        hash = "sha256:1c4bpyh61ampjgk5yh3inrgcpf1z1xv0pshn54ycmpn4dyzv0p2x";
      };
    };
    base-unix = 
    {
      pname = "base-unix";
      version = "base";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base-unix/base-unix.base";
        hash = "sha256:0mpsvb7684g723ylngryh15aqxg3blb7hgmq2fsqjyppr36iyzwg";
      };
    };
    base64 = 
    {
      pname = "base64";
      version = "3.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-base64/releases/download/v3.5.0/base64-v3.5.0.tbz";
        sha256 = "19735bvb3k263hzcvdhn4d5lfv2qscc9ib4q85wgxsvq0p0fk7aq";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/base64/base64.3.5.0";
        hash = "sha256:1xlrmf6920bgsrzycmfp3c6nfylxvfq358cjnjglllh8aiwzsl83";
      };
    };
    bigarray-compat = 
    {
      pname = "bigarray-compat";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/bigarray-compat/archive/v1.0.0.tar.gz";
        sha256 = "1bpmmnxb1yx72aqlbdaqfl18rgz1cq9cf6cqvnfl88mz5dfr4x0d";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigarray-compat/bigarray-compat.1.0.0";
        hash = "sha256:0mcg8csmd60ph17vam1s8xjsl9kp6k77i3mnkbxy0jvkn49m4a0k";
      };
    };
    bigarray-overlap = 
    {
      pname = "bigarray-overlap";
      version = "0.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/dinosaure/overlap/releases/download/v0.2.0/bigarray-overlap-v0.2.0.tbz";
        sha256 = "1v86avafsbyxjccy0y9gny31s2jzb0kd42v3mhcalklx5f044lcy";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune
        bigarray-compat;
        ocaml-freestanding = selection.ocaml-freestanding or null;
        mirage-xen-posix = selection.mirage-xen-posix or null;
        js_of_ocaml-compiler = selection.js_of_ocaml-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigarray-overlap/bigarray-overlap.0.2.0";
        hash = "sha256:06ipffy0dhx8vh8788mhzgmlj7y2f9nxsgkbbklkn5sf5kj7njdh";
      };
    };
    bigstringaf = 
    {
      pname = "bigstringaf";
      version = "0.8.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/inhabitedtype/bigstringaf/archive/0.8.0.tar.gz";
        sha256 = "06w66xnqgv8r92x50b3q6xrymry6fviyj572dw7y76cqdzfph18z";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune conf-pkg-config
        bigarray-compat;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bigstringaf/bigstringaf.0.8.0";
        hash = "sha256:0q3v7v83pj1rf7qzqj5silkx0s8sjpkwjzkvnmnqkyp4aljqnlnb";
      };
    };
    bos = 
    {
      pname = "bos";
      version = "0.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/bos/releases/bos-0.2.1.tbz";
        sha256 = "0dwg7lpaq30rvwc5z1gij36fn9xavvpah1bj8ph9gmhhddw2xmnq";
      };
      opamInputs = 
      {
        inherit (selection) topkg rresult ocamlfind ocamlbuild ocaml logs
        fpath fmt base-unix astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/bos/bos.0.2.1";
        hash = "sha256:1q2crpjb4kync49dlxbwrgbi8c3vbr33i66zf2cnvfjkhjzycs7f";
      };
    };
    ca-certs = 
    {
      pname = "ca-certs";
      version = "0.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ca-certs/releases/download/v0.2.0/ca-certs-v0.2.0.tbz";
        sha256 = "15jfb5zvahs90jsfs7ridqihlka5198z2xrvplj8ddchxfmpx868";
      };
      opamInputs = 
      {
        inherit (selection) x509 rresult ptime ocaml mirage-crypto logs fpath
        dune bos astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ca-certs/ca-certs.0.2.0";
        hash = "sha256:0mdrq201rpf2qzdj2ljggmb39qszjjhv70mp0g22nz2fllb4xmd5";
      };
      buildInputs = [ (pkgs.ca_root_nss or null) ];
    };
    cmdliner = 
    {
      pname = "cmdliner";
      version = "1.0.4";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/cmdliner/releases/cmdliner-1.0.4.tbz";
        sha256 = "1h04q0zkasd0mw64ggh4y58lgzkhg6yhzy60lab8k8zq9ba96ajw";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cmdliner/cmdliner.1.0.4";
        hash = "sha256:05qlm4yp6124w2z10dpdchldfrmgmcr6h31rnxp8qs8mk0xzx48z";
      };
    };
    cohttp = 
    {
      pname = "cohttp";
      version = "4.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v4.0.0/cohttp-v4.0.0.tbz";
        sha256 = "1lnimhmmw5899200k19xrdj4qcj0gbpf6jbwxn84jx425k6s8ymx";
      };
      opamInputs = 
      {
        inherit (selection) uri-sexp uri stringext sexplib0 re ppx_sexp_conv
        ocaml jsonm dune base64;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp/cohttp.4.0.0";
        hash = "sha256:13dkxj716ss2mg30lfflwisn9m8kdpycpdm8zki7bdd32rx2jcs0";
      };
    };
    cohttp-lwt = 
    {
      pname = "cohttp-lwt";
      version = "4.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v4.0.0/cohttp-v4.0.0.tbz";
        sha256 = "1lnimhmmw5899200k19xrdj4qcj0gbpf6jbwxn84jx425k6s8ymx";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv ocaml lwt logs dune
        cohttp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt/cohttp-lwt.4.0.0";
        hash = "sha256:02hxjvgp2dic72jxqj0akrmk082j59yhh47afp8440dzf2v2px5w";
      };
    };
    cohttp-lwt-unix = 
    {
      pname = "cohttp-lwt-unix";
      version = "4.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cohttp/releases/download/v4.0.0/cohttp-v4.0.0.tbz";
        sha256 = "1lnimhmmw5899200k19xrdj4qcj0gbpf6jbwxn84jx425k6s8ymx";
      };
      opamInputs = 
      {
        inherit (selection) ppx_sexp_conv ocaml magic-mime lwt logs fmt dune
        conduit-lwt-unix conduit-lwt cohttp-lwt cmdliner base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cohttp-lwt-unix/cohttp-lwt-unix.4.0.0";
        hash = "sha256:1f52hvwvbfmyfyvvq5pqyfhmhhmy77cz1y87sr2fa6cby80d7lpz";
      };
    };
    coin = 
    {
      pname = "coin";
      version = "0.1.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/coin/releases/download/v0.1.3/coin-v0.1.3.tbz";
        sha256 = "0gr5kw2npq8wpfj1g86sa8jl4lkk00i5bfj7y1drzfgpchb7hbbv";
      };
      opamInputs = 
      {
        inherit (selection) re ocamlfind ocaml menhir dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/coin/coin.0.1.3";
        hash = "sha256:08spcv6fxqzwhfgrwfhk3snncaxyqzsvlw4iksscvmrdjxzdcxm5";
      };
    };
    colombe = 
    {
      pname = "colombe";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/colombe/releases/download/v0.4.0/colombe-v0.4.0.tbz";
        sha256 = "11ddi3y9l11nws2wrzqpm8k7i46dd00i73w1hb83xm7xqsr5h0nq";
      };
      opamInputs = 
      {
        inherit (selection) ocaml-syntax-shims ocaml ipaddr fmt dune
        angstrom;
        emile = selection.emile or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/colombe/colombe.0.4.0";
        hash = "sha256:0rq3ig1k7kywlccx294dn7kbg128b1igq80qnwpq2iwb4m6izg9c";
      };
    };
    conduit = 
    {
      pname = "conduit";
      version = "2.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v2.3.0/conduit-v2.3.0.tbz";
        sha256 = "0bg7alvx3wjbys22hsqfqidjl4sm0ywkrjpy8k8dzs3yjv0c8lnz";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib ppx_sexp_conv ocaml logs ipaddr-sexp
        ipaddr dune astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit/conduit.2.3.0";
        hash = "sha256:1an9qmpzkj0f43b94jdab9w2367v19h63bhrjys67pvbklky0xr8";
      };
    };
    conduit-lwt = 
    {
      pname = "conduit-lwt";
      version = "2.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v2.3.0/conduit-v2.3.0.tbz";
        sha256 = "0bg7alvx3wjbys22hsqfqidjl4sm0ywkrjpy8k8dzs3yjv0c8lnz";
      };
      opamInputs = 
      {
        inherit (selection) sexplib ppx_sexp_conv ocaml lwt dune conduit
        base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt/conduit-lwt.2.3.0";
        hash = "sha256:1mapn30wb037nf0yq88f5xrk6c9pi32npn7z8g6mdaxvp7jqxvmi";
      };
    };
    conduit-lwt-unix = 
    {
      pname = "conduit-lwt-unix";
      version = "2.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-conduit/releases/download/v2.3.0/conduit-v2.3.0.tbz";
        sha256 = "0bg7alvx3wjbys22hsqfqidjl4sm0ywkrjpy8k8dzs3yjv0c8lnz";
      };
      opamInputs = 
      {
        inherit (selection) uri ppx_sexp_conv ocaml lwt logs ipaddr-sexp
        ipaddr dune conduit-lwt ca-certs
        base-unix;
        tls = selection.tls or null;
        lwt_ssl = selection.lwt_ssl or null;
        launchd = selection.launchd or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conduit-lwt-unix/conduit-lwt-unix.2.3.0";
        hash = "sha256:1y8mn5k4fk7rfkr0a6is6xi215jphpdyk63hcwqa3qdmdbpzi2yd";
      };
    };
    conf-gmp = 
    {
      pname = "conf-gmp";
      version = "3";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp/conf-gmp.3";
        hash = "sha256:0xmnv1w1w66c15dgahcgzj980khq7hsva5k9bwc2r1pcj4a2q94d";
      };
      buildInputs = [ (pkgs.gmp or null) (pkgs.gmp-dev or null)
                       (pkgs.gmp-devel or null) (pkgs.libgmp-dev or null) ];
    };
    conf-gmp-powm-sec = 
    {
      pname = "conf-gmp-powm-sec";
      version = "3";
      src = null;
      opamInputs = {
                     inherit (selection) conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-gmp-powm-sec/conf-gmp-powm-sec.3";
        hash = "sha256:1q9c4av0ah791sq81yva4ga1mz5380r4260bjh060d3mzci00hd3";
      };
    };
    conf-libssl = 
    {
      pname = "conf-libssl";
      version = "3";
      src = null;
      opamInputs = {
                     inherit (selection) conf-pkg-config;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-libssl/conf-libssl.3";
        hash = "sha256:02hgl7v0yz2rdjgl90yxw9nhyb80jvjwqbikp45qk71s27kjlhay";
      };
      buildInputs = [ (pkgs.openssl) ];
    };
    conf-pkg-config = 
    {
      pname = "conf-pkg-config";
      version = "2";
      src = null;
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/conf-pkg-config/conf-pkg-config.2";
        hash = "sha256:1rli6809glz5g9xwp4wsjidc39za4n58xcpkamy6fymfnqha225n";
      };
      buildInputs = [ (pkgs.pkgconfig) ];
    };
    cppo = 
    {
      pname = "cppo";
      version = "1.6.8";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-community/cppo/archive/v1.6.8.tar.gz";
        sha256 = "0lxy4xkkkwgs1cj6d9lyzsqi9f6fc9r6cir5imi7yjqrpd86s1by";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cppo/cppo.1.6.8";
        hash = "sha256:0pzd8irqkkkpfgw8nq9d21z9rj5m3qlzixyb7ybfy4b1fwh3n8bp";
      };
    };
    csexp = 
    {
      pname = "csexp";
      version = "1.5.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-dune/csexp/releases/download/1.5.1/csexp-1.5.1.tbz";
        sha256 = "00mc19f89pxpmjl62862ya5kjcfrl8rjzvs00j05h2m9bw3f81fn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/csexp/csexp.1.5.1";
        hash = "sha256:01lc95kz13gpki4xazyh6n20kv1g9inyb5myv240wl2n9v50z8fl";
      };
    };
    cstruct = 
    {
      pname = "cstruct";
      version = "6.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.1/cstruct-v6.0.1.tbz";
        sha256 = "1vcvgba0bb1a0vk1q2cllqxjacanhr3hxgzab4y4alr70j7vnrsa";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct/cstruct.6.0.1";
        hash = "sha256:1fypp9rzvb53h9g8n7ci1k6irpnc5zgww800p86qr81mdz9a5xa4";
      };
    };
    cstruct-sexp = 
    {
      pname = "cstruct-sexp";
      version = "6.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.1/cstruct-v6.0.1.tbz";
        sha256 = "1vcvgba0bb1a0vk1q2cllqxjacanhr3hxgzab4y4alr70j7vnrsa";
      };
      opamInputs = 
      {
        inherit (selection) sexplib ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct-sexp/cstruct-sexp.6.0.1";
        hash = "sha256:0q9ajqisdcw1js2m376br5bg7s7wrdjkzpilb9idcb4401i3bc6i";
      };
    };
    cstruct-unix = 
    {
      pname = "cstruct-unix";
      version = "6.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.1/cstruct-v6.0.1.tbz";
        sha256 = "1vcvgba0bb1a0vk1q2cllqxjacanhr3hxgzab4y4alr70j7vnrsa";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/cstruct-unix/cstruct-unix.6.0.1";
        hash = "sha256:060592f40j2f3lcynn4yazdjxss0j134g8j9y0sm4jx6lw73h46f";
      };
    };
    domain-name = 
    {
      pname = "domain-name";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/domain-name/releases/download/v0.3.0/domain-name-v0.3.0.tbz";
        sha256 = "12kc9p2a2fi1ipc2hyhbzivxpph3npglxwdgvhd6v20rqqdyvnad";
      };
      opamInputs = 
      {
        inherit (selection) ocaml fmt dune astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/domain-name/domain-name.0.3.0";
        hash = "sha256:0jbp70qpx2fbpfnafwrv8qlkazcrw5phmgw1ipxal4la8rq5lp51";
      };
    };
    dune = 
    {
      pname = "dune";
      version = "2.9.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/2.9.1/dune-2.9.1.tbz";
        sha256 = "09lzq04b642iy0ljp59p32lgk3q8iphjh8fkdp69q29l5frgwx5k";
      };
      opamInputs = 
      {
        inherit (selection) base-unix
        base-threads;
        ocamlfind-secondary = selection.ocamlfind-secondary or null;
        ocaml = selection.ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune/dune.2.9.1";
        hash = "sha256:09s6k6kiw081kdh96zhp8ccgf8niw0391brfjl7gva7fansfqaqd";
      };
    };
    dune-configurator = 
    {
      pname = "dune-configurator";
      version = "2.9.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/dune/releases/download/2.9.1/dune-2.9.1.tbz";
        sha256 = "09lzq04b642iy0ljp59p32lgk3q8iphjh8fkdp69q29l5frgwx5k";
      };
      opamInputs = 
      {
        inherit (selection) result ocaml dune csexp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/dune-configurator/dune-configurator.2.9.1";
        hash = "sha256:1aik9w82r8vbb9fsfphpb0vam68s19ggkxprnqr99ygyalp2b71j";
      };
    };
    duration = 
    {
      pname = "duration";
      version = "0.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/duration/releases/download/0.2.0/duration-0.2.0.tbz";
        sha256 = "0sffq704n619ncx3xci31z7mbrayj9w12wpigvzkzxx6lmszn55d";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/duration/duration.0.2.0";
        hash = "sha256:0pk9f1mgbrfn0a026k1219hazsbm9zkzlkmdhn3cm5fn071wwq92";
      };
    };
    emile = 
    {
      pname = "emile";
      version = "1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/dinosaure/emile/releases/download/v1.1/emile-v1.1.tbz";
        sha256 = "0r1141makr0b900aby1gn0fccjv1qcqgyxib3bzq8fxmjqwjan8p";
      };
      opamInputs = 
      {
        inherit (selection) uutf pecu ocaml ipaddr dune bigstringaf base64
        angstrom;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/emile/emile.1.1";
        hash = "sha256:1ncaci71knizw15p79gfy1g9vqpm2lk352k59s90hb47kyyv4ykn";
      };
    };
    eqaf = 
    {
      pname = "eqaf";
      version = "0.8";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/eqaf/releases/download/v0.8/eqaf-v0.8.tbz";
        sha256 = "0xgq3i3vkv9rzbbrg9f1gs9x6cyjdggqdr027sadfdvl21ha2i8i";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/eqaf/eqaf.0.8";
        hash = "sha256:1riqd7dqgq5cf0y7m0fbpszcpazv1kcj1qii3kd0i9wiha46hd9l";
      };
    };
    fiat-p256 = 
    {
      pname = "fiat-p256";
      version = "0.2.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/fiat/releases/download/v0.2.3/fiat-p256-v0.2.3.tbz";
        sha256 = "1q5hfhs9bhl9ph84jj7pv8al51pvxns5ap57lqf136zmjl9in3f2";
      };
      opamInputs = 
      {
        inherit (selection) hex eqaf dune-configurator dune cstruct
        conf-pkg-config
        bigarray-compat;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fiat-p256/fiat-p256.0.2.3";
        hash = "sha256:1mjss68g22p4ac9zhplvksnknjq1cwrx3rqhqq52y8p0qz0bspyw";
      };
    };
    fmt = 
    {
      pname = "fmt";
      version = "0.8.10";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fmt/releases/fmt-0.8.10.tbz";
        sha256 = "1gxjlzbxfl237zzq86cxhyc7r6pdfiy7yphpda0czz29xj7k3jjj";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
        base-unix = selection.base-unix or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fmt/fmt.0.8.10";
        hash = "sha256:1kw1a7h3i66xzl5id0y07zy3z8hnvn9w36y6xm5gg7mmxf6ipw5a";
      };
    };
    fpath = 
    {
      pname = "fpath";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/fpath/releases/fpath-0.7.3.tbz";
        sha256 = "03z7mj0sqdz465rc4drj1gr88l9q3nfs374yssvdjdyhjbqqzc0j";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml astring;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/fpath/fpath.0.7.3";
        hash = "sha256:1pnskgw9fqq4kg1x4sc4vcv9rh0kksilx4qngwafpyss42mqq2i2";
      };
    };
    gmap = 
    {
      pname = "gmap";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/gmap/releases/download/0.3.0/gmap-0.3.0.tbz";
        sha256 = "073wa0lrb0jj706j87cwzf1a8d1ff14100mnrjs8z3xc4ri9xp84";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/gmap/gmap.0.3.0";
        hash = "sha256:1zibwnms9pyvqqchh5mzd48hq32hrs8qcqbai9jwbydnn805ahq5";
      };
    };
    hacl_x25519 = 
    {
      pname = "hacl_x25519";
      version = "0.2.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/hacl/releases/download/v0.2.2/hacl_x25519-v0.2.2.tbz";
        sha256 = "0baprhr46vm6a585qi1jjbajhsh21gjxdklqdl79swzrx2l58rw1";
      };
      opamInputs = 
      {
        inherit (selection) ocaml eqaf dune cstruct
        conf-pkg-config;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hacl_x25519/hacl_x25519.0.2.2";
        hash = "sha256:1fblr48x423qv9nz5aj3imzfg03f19lgcmrld84phdi4lzm3fiah";
      };
    };
    hex = 
    {
      pname = "hex";
      version = "1.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-hex/releases/download/v1.4.0/hex-v1.4.0.tbz";
        sha256 = "07b9y0lmnflsslkrm6xilkj40n8sf2hjqkyqghnk7sw5l0plkqsp";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cstruct bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hex/hex.1.4.0";
        hash = "sha256:18miy6dlzajx135gamwwnmwpl80k9mpykpglkbl0s88spca0y97d";
      };
    };
    hkdf = 
    {
      pname = "hkdf";
      version = "1.0.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/hannesm/ocaml-hkdf/releases/download/v1.0.4/hkdf-v1.0.4.tbz";
        sha256 = "0nzx6vzbc1hh6vx1ly8df4b16lgps6zjpp9mjycsnnn49bddc9mr";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mirage-crypto dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/hkdf/hkdf.1.0.4";
        hash = "sha256:03wcvwhzxipf71aqsh77ly8iygqd6f0pwy04pcga58rifgiys5m2";
      };
    };
    ipaddr = 
    {
      pname = "ipaddr";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.2.0/ipaddr-v5.2.0.tbz";
        sha256 = "1v5pwlg53r8mghz3w3lmav0gw6gmnmlnq37zgnxa10zpq5y273gr";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims ocaml macaddr dune domain-name;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr/ipaddr.5.2.0";
        hash = "sha256:0159nfklpcl6gkg55gimnd0r5bsih2y7f6v8v4h4124n8hchrqm0";
      };
    };
    ipaddr-sexp = 
    {
      pname = "ipaddr-sexp";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.2.0/ipaddr-v5.2.0.tbz";
        sha256 = "1v5pwlg53r8mghz3w3lmav0gw6gmnmlnq37zgnxa10zpq5y273gr";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppx_sexp_conv ocaml ipaddr dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ipaddr-sexp/ipaddr-sexp.5.2.0";
        hash = "sha256:1k2vf49xna4l7pfgr58mcipypq2qdzfpmcrl02zb2wv58106lvg3";
      };
    };
    jsonm = 
    {
      pname = "jsonm";
      version = "1.0.1";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/jsonm/releases/jsonm-1.0.1.tbz";
        sha256 = "1176dcmxb11fnw49b7yysvkjh0kpzx4s48lmdn5psq9vshp5c29w";
      };
      opamInputs = 
      {
        inherit (selection) uutf uchar topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/jsonm/jsonm.1.0.1";
        hash = "sha256:0dj8ibg6j4r4a7v7g6d6q3h4m23jv3pxwc7nam4zzbc7h2k69dy9";
      };
    };
    ke = 
    {
      pname = "ke";
      version = "0.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ke/releases/download/v0.4/ke-v0.4.tbz";
        sha256 = "13c9xy60vmq29mnwpg3h3zgl6gjbjfwbx1s0crfc6xwvark0zxnx";
      };
      opamInputs = 
      {
        inherit (selection) ocaml fmt dune bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ke/ke.0.4";
        hash = "sha256:0wmc14izq43n705nd3qadzq2ydm5h1y9blf72dn2f2bxx5r6glmc";
      };
    };
    lambdasoup = 
    {
      pname = "lambdasoup";
      version = "0.7.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/aantron/lambdasoup/archive/0.7.3.tar.gz";
        sha256 = "1phndl9w3b790gf3cqh589h3zhwy12xwrh5x7km96k90ba35ahih";
      };
      opamInputs = 
      {
        inherit (selection) ocaml markup dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lambdasoup/lambdasoup.0.7.3";
        hash = "sha256:0yjjwjjgmckbjhhvmds00mjpqf5ipqclxr6isdx1h5xvc2cg2akj";
      };
    };
    logs = 
    {
      pname = "logs";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/logs/releases/logs-0.7.0.tbz";
        sha256 = "1jnmd675wmsmdwyb5mx5b0ac66g4c6gpv5s4mrx2j6pb0wla1x46";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        lwt = selection.lwt or null;
        js_of_ocaml = selection.js_of_ocaml or null;
        fmt = selection.fmt or null;
        cmdliner = selection.cmdliner or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/logs/logs.0.7.0";
        hash = "sha256:1k797gb7f2s1hlqyqsq2xyq9gm20l5q2iwh26bs44f3bp3gklg1a";
      };
    };
    lwt = 
    {
      pname = "lwt";
      version = "5.4.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt/archive/refs/tags/5.4.2.tar.gz";
        sha256 = "1jyjq43q9rbrw7ijy8l8rd1rhiy74ix2j1w15q0694rdfbkcnsg1";
      };
      opamInputs = 
      {
        inherit (selection) seq result ocplib-endian ocaml mmap
        dune-configurator dune
        cppo;
        ocaml-syntax-shims = selection.ocaml-syntax-shims or null;
        conf-libev = selection.conf-libev or null;
        base-unix = selection.base-unix or null;
        base-threads = selection.base-threads or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt/lwt.5.4.2";
        hash = "sha256:1jss4a1pihrjdbcnfkva8i0p14ahx2ia6qwfjrqjkzir5fwp2n7j";
      };
    };
    lwt_ssl = 
    {
      pname = "lwt_ssl";
      version = "1.1.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/lwt_ssl/archive/1.1.3.tar.gz";
        sha256 = "0dxxkif4a667ndk14sn8ka4x4gck0gvw4sc12jb84rcq5k15jlkp";
      };
      opamInputs = 
      {
        inherit (selection) ssl ocaml lwt dune base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/lwt_ssl/lwt_ssl.1.1.3";
        hash = "sha256:1fri84nnlgq0zcmmr2hk19hj8a1d2wg98p41vyq27nj6wmg6h2r2";
      };
    };
    macaddr = 
    {
      pname = "macaddr";
      version = "5.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-ipaddr/releases/download/v5.2.0/ipaddr-v5.2.0.tbz";
        sha256 = "1v5pwlg53r8mghz3w3lmav0gw6gmnmlnq37zgnxa10zpq5y273gr";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/macaddr/macaddr.5.2.0";
        hash = "sha256:1w7hg0i037a8f1rggr39m0679qhnp4xzd4ikxvy6573nf3myl2b1";
      };
    };
    magic-mime = 
    {
      pname = "magic-mime";
      version = "1.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-magic-mime/releases/download/v1.2.0/magic-mime-v1.2.0.tbz";
        sha256 = "1xcl0si6zgczfx1788y0qm5wir15fcfd1mczzki9gpgq01svc8gi";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/magic-mime/magic-mime.1.2.0";
        hash = "sha256:0cd3l2cjh2rlvp1r9l5fb0jxhn5176qjw042py9xq999zp09kp21";
      };
    };
    markup = 
    {
      pname = "markup";
      version = "1.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/aantron/markup.ml/archive/1.0.2.tar.gz";
        sha256 = "1d6d95mj6m5jv4x9l4hv8qszy99f95qn7rcxndjf4pjmfv4sdix6";
      };
      opamInputs = 
      {
        inherit (selection) uutf uchar ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/markup/markup.1.0.2";
        hash = "sha256:02nm8nr250mjnapf5j0d3gnqah0d9zmk4wm61hxg06l0yli881a3";
      };
    };
    menhir = 
    {
      pname = "menhir";
      version = "20211012";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211012/archive.tar.gz";
        sha256 = "0sjhh4r793p297ywjrygjjz9hmhrmld0vfm53kqqcimp8vr1wxd2";
      };
      opamInputs = 
      {
        inherit (selection) ocaml menhirSdk menhirLib dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhir/menhir.20211012";
        hash = "sha256:17ryhvbg6yaxsai77s2d37sf132rvkcv57ilm33nl5zlgclw6b60";
      };
    };
    menhirLib = 
    {
      pname = "menhirLib";
      version = "20211012";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211012/archive.tar.gz";
        sha256 = "0sjhh4r793p297ywjrygjjz9hmhrmld0vfm53kqqcimp8vr1wxd2";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirLib/menhirLib.20211012";
        hash = "sha256:0m32qmix5g25h883154v64429yjvf8bjmf583hxfw1mnhl4fplqh";
      };
    };
    menhirSdk = 
    {
      pname = "menhirSdk";
      version = "20211012";
      src = pkgs.fetchurl 
      {
        url = "https://gitlab.inria.fr/fpottier/menhir/-/archive/20211012/archive.tar.gz";
        sha256 = "0sjhh4r793p297ywjrygjjz9hmhrmld0vfm53kqqcimp8vr1wxd2";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/menhirSdk/menhirSdk.20211012";
        hash = "sha256:0gw6smpyzmb6g25ch74ji7asf1f8pbwp8ngpz7hn6ynnr6njcyln";
      };
    };
    mirage-crypto = 
    {
      pname = "mirage-crypto";
      version = "0.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.3/mirage-crypto-v0.10.3.tbz";
        sha256 = "02whi8gb8wp7drczl7rfhg7mm0w1bcxdjh4a1qzjrc2rblv10yd2";
      };
      opamInputs = 
      {
        inherit (selection) ocaml eqaf dune-configurator dune cstruct
        conf-pkg-config
        bigarray-compat;
        ocaml-freestanding = selection.ocaml-freestanding or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto/mirage-crypto.0.10.3";
        hash = "sha256:065h09vig3r8vj2vvzvvdwarisxm6pakh8jwjq6n8cxczzwgai4n";
      };
    };
    mirage-crypto-pk = 
    {
      pname = "mirage-crypto-pk";
      version = "0.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.3/mirage-crypto-v0.10.3.tbz";
        sha256 = "02whi8gb8wp7drczl7rfhg7mm0w1bcxdjh4a1qzjrc2rblv10yd2";
      };
      opamInputs = 
      {
        inherit (selection) zarith sexplib rresult ppx_sexp_conv ocaml
        mirage-crypto-rng mirage-crypto eqaf dune cstruct
        conf-gmp-powm-sec;
        zarith-freestanding = selection.zarith-freestanding or null;
        mirage-runtime = selection.mirage-runtime or null;
        mirage-no-xen = selection.mirage-no-xen or null;
        mirage-no-solo5 = selection.mirage-no-solo5 or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-pk/mirage-crypto-pk.0.10.3";
        hash = "sha256:072amnz526k36wlmdwy7qqhwqq4gbxm7sfc60iyw207mk1mskhpg";
      };
    };
    mirage-crypto-rng = 
    {
      pname = "mirage-crypto-rng";
      version = "0.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mirage-crypto/releases/download/v0.10.3/mirage-crypto-v0.10.3.tbz";
        sha256 = "02whi8gb8wp7drczl7rfhg7mm0w1bcxdjh4a1qzjrc2rblv10yd2";
      };
      opamInputs = 
      {
        inherit (selection) ocaml mtime mirage-crypto lwt logs duration
        dune-configurator dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-crypto-rng/mirage-crypto-rng.0.10.3";
        hash = "sha256:064r6pmg7zzsalk1zzhsvxnsw360kgn4im47z8iv126mb6qjlcrk";
      };
    };
    mirage-no-solo5 = 
    {
      pname = "mirage-no-solo5";
      version = "1";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-no-solo5/mirage-no-solo5.1";
        hash = "sha256:18h50v7lp39sis6jy46h35vij0v1z5fr76c4y2h4b72c40fwwck1";
      };
    };
    mirage-no-xen = 
    {
      pname = "mirage-no-xen";
      version = "1";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mirage-no-xen/mirage-no-xen.1";
        hash = "sha256:1nvmvay3nkl8ljw9f46dwv3jppqbbkp0pxf9f1gq4spckb8ysmkh";
      };
    };
    mmap = 
    {
      pname = "mmap";
      version = "1.1.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mmap/releases/download/v1.1.0/mmap-v1.1.0.tbz";
        sha256 = "0l6waidal2n8mkdn74avbslvc10sf49f5d889n838z03pra5chsc";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mmap/mmap.1.1.0";
        hash = "sha256:1snhaf6mixmmb49gcin5wmbz4bfjz406mip4556lids8ajm22ibh";
      };
    };
    mrmime = 
    {
      pname = "mrmime";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/mrmime/releases/download/v0.4.0/mrmime-v0.4.0.tbz";
        sha256 = "1x20xzibcwra3i2k8w7f5dcq1kbwv0k1f7jcjl1q02nhnjb6vn9q";
      };
      opamInputs = 
      {
        inherit (selection) uutf unstrctrd rresult rosetta ptime prettym pecu
        ocaml ke ipaddr fmt emile dune bigstringaf bigarray-overlap
        bigarray-compat base64 angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mrmime/mrmime.0.4.0";
        hash = "sha256:1q3wv9glvv9gbhafhbc77vcb1blfpc021ddrflh82b4k7iw69j29";
      };
    };
    mtime = 
    {
      pname = "mtime";
      version = "1.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/mtime/releases/mtime-1.3.0.tbz";
        sha256 = "0syilgk4nzscacsswnvgwqlf0n0lhs221jss8gc8z9igw2x4sgsq";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild
        ocaml;
        js_of_ocaml = selection.js_of_ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/mtime/mtime.1.3.0";
        hash = "sha256:18503vvcqz052k00hlmdda4227zvwb85c189ppkni8m9m01xza0z";
      };
    };
    num = 
    {
      pname = "num";
      version = "1.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/num/archive/v1.4.tar.gz";
        sha256 = "090gl27g84r3s2b12vgkz8fp269jqlrhx4lpg7008yviisv8hl01";
      };
      opamInputs = {
                     inherit (selection) ocamlfind ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/num/num.1.4";
        hash = "sha256:04wb8ww165lsifn36jcrxw5zs87id5kib6rilq6zh6qhzvij88pf";
      };
    };
    ocaml = 
    {
      pname = "ocaml";
      version = "4.10.2";
      src = null;
      opamInputs = 
      {
        inherit (selection)
        ocaml-config;
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml/ocaml.4.10.2";
        hash = "sha256:07qfra4v0jj5pp75ccx4ymxkgr8b111m5rfqcv1zdkymxdl42jzg";
      };
    };
    ocaml-base-compiler = 
    {
      pname = "ocaml-base-compiler";
      version = "4.10.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml/archive/4.10.2.tar.gz";
        sha256 = "0rnqy5i93jjx5b8a6479px1k8kvhnap5mkwjvww06vzkf06nx8ks";
      };
      opamInputs = {
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-base-compiler/ocaml-base-compiler.4.10.2";
        hash = "sha256:1iicvnh3dh8vhkc1xvrgki0n1msfdr34kv7nafs3x8px9w2yprld";
      };
    };
    ocaml-compiler-libs = 
    {
      pname = "ocaml-compiler-libs";
      version = "v0.12.4";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ocaml-compiler-libs/releases/download/v0.12.4/ocaml-compiler-libs-v0.12.4.tbz";
        sha256 = "0q3pl20pkx410gw9g4m26qq6dmzi9qan2dqlga6c2ifc6pnckjaf";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-compiler-libs/ocaml-compiler-libs.v0.12.4";
        hash = "sha256:1blynia10j8vyj559kcvc7ic69zq6qjjn092fcsjzfw6czd8ya2c";
      };
    };
    ocaml-config = 
    {
      pname = "ocaml-config";
      version = "1";
      src = null;
      opamInputs = 
      {
        ocaml-variants = selection.ocaml-variants or null;
        ocaml-system = selection.ocaml-system or null;
        ocaml-base-compiler = selection.ocaml-base-compiler or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-config/ocaml-config.1";
        hash = "sha256:1gc3pyhb64j8a91bgbpy9fzljpb1ps2ylgw31ldx879vdkk46nhp";
      };
    };
    ocaml-syntax-shims = 
    {
      pname = "ocaml-syntax-shims";
      version = "1.0.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz";
        sha256 = "1j7848khli4p7j8i2kmnvhdnhcwhy3zgdpf5ds5ic30ax69y3cl9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocaml-syntax-shims/ocaml-syntax-shims.1.0.0";
        hash = "sha256:0qnm1db0298yqcn6j9fmb0l4gr5nhcar8plskj39917invyamgd2";
      };
    };
    ocamlbuild = 
    {
      pname = "ocamlbuild";
      version = "0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocamlbuild/archive/0.14.0.tar.gz";
        sha256 = "0y1fskw9rg2y1zgb7whv3v8v4xw04svgxslf3856q2aqd7lrrcl7";
      };
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlbuild/ocamlbuild.0.14.0";
        hash = "sha256:1r5qnrcxfypzyvjvb3zd9f66kr5ldxdl3g9rsi3pb6040krqb5w7";
      };
    };
    ocamlfind = 
    {
      pname = "ocamlfind";
      version = "1.9.1";
      src = pkgs.fetchurl 
      {
        url = "http://download.camlcity.org/download/findlib-1.9.1.tar.gz";
        sha256 = "1qhgk25avmz4l4g47g8jvk0k1g9p9d5hbdrwpz2693a8ajyvhhib";
      };
      opamInputs = 
      {
        inherit (selection) ocaml;
        graphics = selection.graphics or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocamlfind/ocamlfind.1.9.1";
        hash = "sha256:11avrzm0gdc6mz7dazr8q18ir5429ckc36s2mv0l8722znq8lc3k";
      };
    };
    ocplib-endian = 
    {
      pname = "ocplib-endian";
      version = "1.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/OCamlPro/ocplib-endian/archive/1.1.tar.gz";
        sha256 = "0qy5q7p11gxi5anhvi8jj6mr80ml0ih8lax5k579rsr2hsp3sns5";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune cppo base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ocplib-endian/ocplib-endian.1.1";
        hash = "sha256:0j5ymxa4ky208k8m4bprvmvbqf9jnr4d0xwdaivznbv85jq9hw4q";
      };
    };
    parsexp = 
    {
      pname = "parsexp";
      version = "v0.14.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/parsexp/archive/refs/tags/v0.14.1.tar.gz";
        sha256 = "1c0faqydsvn06qxwnyns567frmg9lxs2fv2bsy20ngyii16fcq04";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/parsexp/parsexp.v0.14.1";
        hash = "sha256:099c589d87lk87kys3imlfdfx1x4hjbagsxfiblp343z7q4n71qj";
      };
    };
    pecu = 
    {
      pname = "pecu";
      version = "0.6";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/pecu/releases/download/v0.6/pecu-v0.6.tbz";
        sha256 = "1iz5jj9lyl1pah8dfni4wv0qml0ir5zknv4zhw7v50sc8kdbglm9";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/pecu/pecu.0.6";
        hash = "sha256:1h3k00rxhhs31q2inxrypjj8dk3qhnn0bz6xlj3p5hs92frww3s3";
      };
    };
    ppx_cstruct = 
    {
      pname = "ppx_cstruct";
      version = "6.0.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-cstruct/releases/download/v6.0.1/cstruct-v6.0.1.tbz";
        sha256 = "1vcvgba0bb1a0vk1q2cllqxjacanhr3hxgzab4y4alr70j7vnrsa";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib ppxlib ocaml dune cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_cstruct/ppx_cstruct.6.0.1";
        hash = "sha256:0xqg65rbng791zgn2y28z1jsr3g6yaxyllx60dy13646vql6kkbx";
      };
    };
    ppx_derivers = 
    {
      pname = "ppx_derivers";
      version = "1.2.1";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz";
        sha256 = "159vqy616ni18mn0dlv8c2y4h7mb4hahwjn53yrr59yyhzhmwndn";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_derivers/ppx_derivers.1.2.1";
        hash = "sha256:0r8rjp4m5jfbf3wz8qlgh82pxjws4arjwxhqq0zjglby6l6h8p3x";
      };
    };
    ppx_sexp_conv = 
    {
      pname = "ppx_sexp_conv";
      version = "v0.14.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/ppx_sexp_conv/archive/v0.14.3.tar.gz";
        sha256 = "0fbnkhsd6yphc49pa21nlmbik99n7qkaz8l9paq96v012ipg9h9g";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 ppxlib ocaml dune base;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppx_sexp_conv/ppx_sexp_conv.v0.14.3";
        hash = "sha256:03c4ar76g1sz2y35a9jbffw957i17ixwd7ky8cg5ss7m7jl7x1fs";
      };
    };
    ppxlib = 
    {
      pname = "ppxlib";
      version = "0.23.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml-ppx/ppxlib/releases/download/0.23.0/ppxlib-0.23.0.tbz";
        sha256 = "1r8jzrqrklwgdbc9qwmp36shhkwgjvrr9nj7rxma3mdrhv0kcn0v";
      };
      opamInputs = 
      {
        inherit (selection) stdlib-shims sexplib0 ppx_derivers
        ocaml-compiler-libs ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ppxlib/ppxlib.0.23.0";
        hash = "sha256:1hym210g2ggbzqlnkshn8c3yihcrlqklwmy4ihsm09k5ln7wa9al";
      };
    };
    prettym = 
    {
      pname = "prettym";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/dinosaure/prettym/releases/download/0.0.2/prettym-0.0.2.tbz";
        sha256 = "1df5zccnmqc30rla53wbvk9j24jdlmwbfj9zhzcla11vv2fh6aq8";
      };
      opamInputs = 
      {
        inherit (selection) ocaml ke fmt dune bigstringaf bigarray-overlap
        bigarray-compat;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/prettym/prettym.0.0.2";
        hash = "sha256:1qbjss8d8c5pf4x93i0q9lmb5fs6pxb9qs52r1ypkhzw4444nbwi";
      };
    };
    ptime = 
    {
      pname = "ptime";
      version = "0.8.5";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/ptime/releases/ptime-0.8.5.tbz";
        sha256 = "1fxq57xy1ajzfdnvv5zfm7ap2nf49znw5f9gbi4kb9vds942ij27";
      };
      opamInputs = 
      {
        inherit (selection) topkg result ocamlfind ocamlbuild
        ocaml;
        js_of_ocaml = selection.js_of_ocaml or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ptime/ptime.0.8.5";
        hash = "sha256:0ldzn2jmz8c3n9rr4mqyfa92lkb3378cmik3klznbln7lsf4fa1v";
      };
    };
    re = 
    {
      pname = "re";
      version = "1.10.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/ocaml-re/releases/download/1.10.3/re-1.10.3.tbz";
        sha256 = "1fqfg609996bgxr14yyfxhvl6hm9c1j0mm2xjdjigqrzgyb4crc4";
      };
      opamInputs = {
                     inherit (selection) seq ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/re/re.1.10.3";
        hash = "sha256:1f2xgscc07g800ia8z43i1p377dj2fjdrpzsqgzvw1dnplwnklya";
      };
    };
    result = 
    {
      pname = "result";
      version = "1.5";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/janestreet/result/releases/download/1.5/result-1.5.tbz";
        sha256 = "0cpfp35fdwnv3p30a06wd0py3805qxmq3jmcynjc3x2qhlimwfkw";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/result/result.1.5";
        hash = "sha256:0ybmvlisfz5swvbcq855czz1ysv9zxmb79f1m0x8284hczmfm98f";
      };
    };
    rosetta = 
    {
      pname = "rosetta";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/rosetta/releases/download/v0.3.0/rosetta-v0.3.0.tbz";
        sha256 = "0r2553gb8j3jxsrwmgnxxikmymxjid9kfl987gr06sxgg27n7yyz";
      };
      opamInputs = 
      {
        inherit (selection) yuscii uuuu ocaml dune coin;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/rosetta/rosetta.0.3.0";
        hash = "sha256:0jsdsackyzlk0dhag17pff2nbzwvjmnsahkf2nxww9kz2xbd9imv";
      };
    };
    rresult = 
    {
      pname = "rresult";
      version = "0.7.0";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/rresult/releases/rresult-0.7.0.tbz";
        sha256 = "0h2mjyzhay1p4k7n0mzaa7hlc7875kiy6m1i3r1n03j6hddpzahi";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/rresult/rresult.0.7.0";
        hash = "sha256:0131az6qj1086hi1kjc7x99x1q4c0z3axjwd1wbmr6c6r6nnaj6y";
      };
    };
    rss_to_mail = 
    {
      pname = "rss_to_mail";
      version = "dev";
      src = self.directSrc "rss_to_mail";
      opamInputs = 
      {
        inherit (selection) xmlm x509 uri tyxml-ppx tyxml sexplib0 sexplib
        sendmail-lwt ptime ocaml mrmime markup lwt_ssl lwt logs lambdasoup
        emile dune cstruct-unix colombe cohttp-lwt-unix cmdliner;
      };
      opamSrc = "rss_to_mail.opam";
    };
    sendmail = 
    {
      pname = "sendmail";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/colombe/releases/download/v0.4.0/colombe-v0.4.0.tbz";
        sha256 = "11ddi3y9l11nws2wrzqpm8k7i46dd00i73w1hb83xm7xqsr5h0nq";
      };
      opamInputs = 
      {
        inherit (selection) tls ocaml logs dune colombe base64;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sendmail/sendmail.0.4.0";
        hash = "sha256:1bh1xvlimy57cdijwk5z90ngblyjc9f102rhq63lfvvpvpikhnly";
      };
    };
    sendmail-lwt = 
    {
      pname = "sendmail-lwt";
      version = "0.4.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/colombe/releases/download/v0.4.0/colombe-v0.4.0.tbz";
        sha256 = "11ddi3y9l11nws2wrzqpm8k7i46dd00i73w1hb83xm7xqsr5h0nq";
      };
      opamInputs = 
      {
        inherit (selection) x509 tls sendmail ocaml lwt dune domain-name;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sendmail-lwt/sendmail-lwt.0.4.0";
        hash = "sha256:1gqs8vwdm8zcih7cxdjks2pvxq2bg942n0kfndirkpaxsnsmairv";
      };
    };
    seq = 
    {
      pname = "seq";
      version = "base";
      src = null;
      opamInputs = {
                     inherit (selection) ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/seq/seq.base";
        hash = "sha256:1vm8mk6zm2q3fwnkprl6jib048zr4ysldw0bl74x6wwbxj0vx6k9";
      };
    };
    sexplib = 
    {
      pname = "sexplib";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib-v0.14.0.tar.gz";
        sha256 = "12rlnc6fcrjfdn3gs2agi418sj54ighhs6dfll37zcv7mgywblm2";
      };
      opamInputs = 
      {
        inherit (selection) sexplib0 parsexp ocaml num dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib/sexplib.v0.14.0";
        hash = "sha256:1nlzjkx60d4z09b15nq35ivzl6akk3svq7nl4vv5swhsmj8gvpl4";
      };
    };
    sexplib0 = 
    {
      pname = "sexplib0";
      version = "v0.14.0";
      src = pkgs.fetchurl 
      {
        url = "https://ocaml.janestreet.com/ocaml-core/v0.14/files/sexplib0-v0.14.0.tar.gz";
        sha256 = "0adrc0r1vvvr41dcpj8jwkzh1dfgqf0mks9xlnnskqfm3a51iavg";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/sexplib0/sexplib0.v0.14.0";
        hash = "sha256:0k9vkjbiibja48c0yayal7xwyik3h3c3v4dwd3j7jbmras63ig2c";
      };
    };
    ssl = 
    {
      pname = "ssl";
      version = "0.5.10";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/savonet/ocaml-ssl/archive/v0.5.10.tar.gz";
        sha256 = "0vcc8p6i8lhs59y3ycikllc6j1adh9syh63g5ibnrp3yz3lk2cwl";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune-configurator dune conf-libssl
        base-unix;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/ssl/ssl.0.5.10";
        hash = "sha256:1vyxxwa7p5dz94d52gra6kljcnn76c9vy6a5x79npynpa3mv6fd4";
      };
    };
    stdlib-shims = 
    {
      pname = "stdlib-shims";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz";
        sha256 = "0jnqsv6pqp5b5g7lcjwgd75zqqvcwcl5a32zi03zg1kvj79p5gxs";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stdlib-shims/stdlib-shims.0.3.0";
        hash = "sha256:19g9dnaxyh2ajz6pdczdsqzzvsmfrxwx6f613inkr31jw5hrqkiz";
      };
    };
    stringext = 
    {
      pname = "stringext";
      version = "1.6.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz";
        sha256 = "1sh6nafi3i9773j5mlwwz3kxfzdjzsfqj2qibxhigawy5vazahfv";
      };
      opamInputs = 
      {
        inherit (selection) ocaml dune base-bytes;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/stringext/stringext.1.6.0";
        hash = "sha256:1yjysjb40yjhqmcx3z12y2nmr2qy215qdnvdns1hxip0fjcd4zkz";
      };
    };
    tls = 
    {
      pname = "tls";
      version = "0.12.8";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-tls/releases/download/v0.12.8/tls-v0.12.8.tbz";
        sha256 = "0sgppvfnamfnsglw1cl801i1xqkxbs33g40kwmmqj2vqjcarm26a";
      };
      opamInputs = 
      {
        inherit (selection) x509 sexplib ptime ppx_sexp_conv ppx_cstruct
        ocaml mirage-crypto-rng mirage-crypto-pk mirage-crypto lwt logs hkdf
        hacl_x25519 fmt fiat-p256 dune domain-name cstruct-sexp cstruct;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tls/tls.0.12.8";
        hash = "sha256:0mzi229apiffbmldxhaz24jy9yblv4xj0m0iswc7bh378a424l7d";
      };
    };
    topkg = 
    {
      pname = "topkg";
      version = "1.0.4";
      src = pkgs.fetchurl 
      {
        url = "https://erratique.ch/software/topkg/releases/topkg-1.0.4.tbz";
        sha256 = "1kzw5cxkizcvh4rgzwgpjlj9hfxfk6yr686bxx6wrbsfs8as371k";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/topkg/topkg.1.0.4";
        hash = "sha256:0gvngd4nayhhw02gcsljvmx6jkjpv9m3mqwpgimcfq04h0cf4knb";
      };
    };
    tyxml = 
    {
      pname = "tyxml";
      version = "4.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/tyxml/releases/download/4.5.0/tyxml-4.5.0.tbz";
        sha256 = "0s30f72m457c3gbdmdwbx7ls9zg806nvm83aiz9qkpglbppwr6n6";
      };
      opamInputs = 
      {
        inherit (selection) uutf seq re ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tyxml/tyxml.4.5.0";
        hash = "sha256:1lw91vsiijp4n6vgpfbws72c1v7a1b0v1fkxd7spasl8z27ljq2g";
      };
    };
    tyxml-ppx = 
    {
      pname = "tyxml-ppx";
      version = "4.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/tyxml/releases/download/4.5.0/tyxml-4.5.0.tbz";
        sha256 = "0s30f72m457c3gbdmdwbx7ls9zg806nvm83aiz9qkpglbppwr6n6";
      };
      opamInputs = 
      {
        inherit (selection) tyxml-syntax tyxml ppxlib ocaml markup dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tyxml-ppx/tyxml-ppx.4.5.0";
        hash = "sha256:1ghrc4hx1394d8zvw0ndy04wk3cg31cz0vm8y39z5vh6kgxv52w6";
      };
    };
    tyxml-syntax = 
    {
      pname = "tyxml-syntax";
      version = "4.5.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocsigen/tyxml/releases/download/4.5.0/tyxml-4.5.0.tbz";
        sha256 = "0s30f72m457c3gbdmdwbx7ls9zg806nvm83aiz9qkpglbppwr6n6";
      };
      opamInputs = 
      {
        inherit (selection) uutf re ppxlib ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/tyxml-syntax/tyxml-syntax.4.5.0";
        hash = "sha256:1fr7awxcfwzha68bh36crkvgrrda1adpbaxnsr8nag87283d7hql";
      };
    };
    uchar = 
    {
      pname = "uchar";
      version = "0.0.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz";
        sha256 = "1w2saw7zanf9m9ffvz2lvcxvlm118pws2x1wym526xmydhqpyfa7";
      };
      opamInputs = {
                     inherit (selection) ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uchar/uchar.0.0.2";
        hash = "sha256:17sfpyj5a1z3knnjvnfa5vql6cj2x9pzgzk8w4jrvd2zii2bwpcl";
      };
    };
    unstrctrd = 
    {
      pname = "unstrctrd";
      version = "0.3";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/dinosaure/unstrctrd/releases/download/v0.3/unstrctrd-v0.3.tbz";
        sha256 = "0nzdinks5j5drk3ihj0p9vv9wc7zdw9rz3y886360xxrlvlv2mbk";
      };
      opamInputs = 
      {
        inherit (selection) uutf ocaml dune angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/unstrctrd/unstrctrd.0.3";
        hash = "sha256:1r3j78vy4lvyng6b3ljxfp23z0cmajljwxsx8yddl00dbgaidwnl";
      };
    };
    uri = 
    {
      pname = "uri";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.2.0/uri-v4.2.0.tbz";
        sha256 = "0szifda6yism5vn5jdizkha3ad0xk6zw4xgfl8g77dnv83ci7h65";
      };
      opamInputs = 
      {
        inherit (selection) stringext ocaml dune angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri/uri.4.2.0";
        hash = "sha256:1s0rbjixhl1ypxv9xxmldlmxm6gj9rrzmcgydp8dna4n0wza4hbf";
      };
    };
    uri-sexp = 
    {
      pname = "uri-sexp";
      version = "4.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/ocaml-uri/releases/download/v4.2.0/uri-v4.2.0.tbz";
        sha256 = "0szifda6yism5vn5jdizkha3ad0xk6zw4xgfl8g77dnv83ci7h65";
      };
      opamInputs = 
      {
        inherit (selection) uri sexplib0 ppx_sexp_conv dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uri-sexp/uri-sexp.4.2.0";
        hash = "sha256:0n2g1p9hn7n38pdxyyjahbaa5z37nw1jw1mxgpad7jy86slfilac";
      };
    };
    uutf = 
    {
      pname = "uutf";
      version = "1.0.2";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/uutf/releases/uutf-1.0.2.tbz";
        sha256 = "1nx1rly3qj23jzn9yk3x6fwqimcxjd84kv5859vvhdg56psq26p6";
      };
      opamInputs = 
      {
        inherit (selection) uchar topkg ocamlfind ocamlbuild
        ocaml;
        cmdliner = selection.cmdliner or null;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uutf/uutf.1.0.2";
        hash = "sha256:1j4hkk196lg1dsnf6jb1n8y3na606lkfb5vlr0gjb53qc7pdh6cy";
      };
    };
    uuuu = 
    {
      pname = "uuuu";
      version = "0.2.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/uuuu/releases/download/v0.2.0/uuuu-v0.2.0.tbz";
        sha256 = "0czgg2hp8r4r0piki193cl94gyqa28jvk51c2k9x7cjlr16nr327";
      };
      opamInputs = 
      {
        inherit (selection) re ocamlfind ocaml menhir dune angstrom;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/uuuu/uuuu.0.2.0";
        hash = "sha256:07bzj3ns09wx4ivbsd62mp8pjj394wp2labnyzspicnv4vl5c3mb";
      };
    };
    x509 = 
    {
      pname = "x509";
      version = "0.11.2";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirleft/ocaml-x509/releases/download/v0.11.2/x509-v0.11.2.tbz";
        sha256 = "1b4lcphmlyjhdgqi0brakgjp3diwmrj1y9hx87svi5xklw3zik22";
      };
      opamInputs = 
      {
        inherit (selection) rresult ptime ocaml mirage-crypto-pk
        mirage-crypto logs gmap fmt dune domain-name cstruct base64
        asn1-combinators;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/x509/x509.0.11.2";
        hash = "sha256:0cfslppx7c8kp0yjqlfaw4nwpl5iryk6qv3m4qxh646s8yfv2j1h";
      };
    };
    xmlm = 
    {
      pname = "xmlm";
      version = "1.3.0";
      src = pkgs.fetchurl 
      {
        url = "http://erratique.ch/software/xmlm/releases/xmlm-1.3.0.tbz";
        sha256 = "1rrdxg5kh9zaqmgapy9bhdqyxbbvxxib3bdfg1vhw4rrkp1z0x8n";
      };
      opamInputs = 
      {
        inherit (selection) topkg ocamlfind ocamlbuild ocaml;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/xmlm/xmlm.1.3.0";
        hash = "sha256:1sllk1bcqdbb67fcimwb9j4z8n0z1z49aqgy65vwsigzymmnjz14";
      };
    };
    yuscii = 
    {
      pname = "yuscii";
      version = "0.3.0";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/mirage/yuscii/releases/download/v0.3.0/yuscii-v0.3.0.tbz";
        sha256 = "1cbla1fw8ygcmid9v220bk9ki9n0v3wk0yc84rrm852xaznqg3gg";
      };
      opamInputs = {
                     inherit (selection) ocaml dune;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/yuscii/yuscii.0.3.0";
        hash = "sha256:1n43qm6bz51ka7b4g9zhvlkcjmqkz9jf5zm1g02i4sh7gacpi91w";
      };
    };
    zarith = 
    {
      pname = "zarith";
      version = "1.12";
      src = pkgs.fetchurl 
      {
        url = "https://github.com/ocaml/Zarith/archive/release-1.12.tar.gz";
        sha256 = "1098xpqsq3gwpz9k2gc6ahiz2zk0z0xxi1lwc07nvj2570y5ccnc";
      };
      opamInputs = 
      {
        inherit (selection) ocamlfind ocaml conf-gmp;
      };
      opamSrc = repoPath (repos.opam-repository.src) 
      {
        package = "packages/zarith/zarith.1.12";
        hash = "sha256:03by05004bgfkfllpacf3vk1h8i6q7wzwi7cgxy0nyj5ffga0ggh";
      };
    };
  };
}

